version: "2"
services: 
    web: 
        image: node:14
        entrypoint: /app/entrypoint.sh
        working_dir: /app/
        network_mode: host
        volumes:
            - .:/app/
        ports: 
            - 8082:8082
        environment: 
            - NODE_ENV: production
